import user_img from "../../src/assets/icon/user.svg?react";
export const data = [
  {
    id: 1,
    title: "comedy",
    video: "https://www.freepik.com/free-photos-vectors/default-user",
    view: 1200,
    time: 600,
    user: {
      img: user_img,
      name: "About users",
    },
  },
  {
    id: 2,
    title: "Lab",
    video: "https://www.freepik.com/free-photos-vectors/default-user",
    view: 1200,
    time: 600,
    user: {
      img: user_img,
      name: "About users",
    },
  },
  {
    id: 3,
    title: "Hero",
    video: "https://www.freepik.com/free-photos-vectors/default-user",
    view: 1200,
    time: 600,
    user: {
      img: user_img,
      name: "About users",
    },
  },
  {
    id: 4,
    title: "Marvel",
    video: "https://www.freepik.com/free-photos-vectors/default-user",
    view: 1200,
    time: 600,
    user: {
      img: user_img,
      name: "About users",
    },
  },
  {
    id: 1,
    title: "post",
    video: "https://www.freepik.com/free-photos-vectors/default-user",
    view: 1200,
    time: 600,
    user: {
      img: user_img,
      name: "About users",
    },
  },
  {
    id: 1,
    title: "tragedy",
    video: "https://www.freepik.com/free-photos-vectors/default-user",
    view: 1200,
    time: 600,
    user: {
      img: user_img,
      name: "About users",
    },
  },
  {
    id: 1,
    title: "drama",
    video: "https://www.freepik.com/free-photos-vectors/default-user",
    view: 1200,
    time: 600,
    user: {
      img: user_img,
      name: "About users",
    },
  },
  {
    id: 1,
    title: "thriller",
    video: "https://www.freepik.com/free-photos-vectors/default-user",
    view: 1200,
    time: 600,
    user: {
      img: user_img,
      name: "About users",
    },
  },
  {
    id: 1,
    title: "horror",
    video: "https://www.freepik.com/free-photos-vectors/default-user",
    view: 1200,
    time: 600,
    user: {
      img: user_img,
      name: "About users",
    },
  },
  {
    id: 1,
    title: "backstage",
    video: "https://www.freepik.com/free-photos-vectors/default-user",
    view: 1200,
    time: 600,
    user: {
      img: user_img,
      name: "About users",
    },
  },
  {
    id: 1,
    title: "utopic",
    video: "https://www.freepik.com/free-photos-vectors/default-user",
    view: 1200,
    time: 600,
    user: {
      img: user_img,
      name: "About users",
    },
  },
  {
    id: 1,
    title: "vidoecopy",
    video: "https://www.freepik.com/free-photos-vectors/default-user",
    view: 1200,
    time: 600,
    user: {
      img: user_img,
      name: "About users",
    },
  },
  {
    id: 1,
    title: "anonim",
    video: "https://www.freepik.com/free-photos-vectors/default-user",
    view: 1200,
    time: 600,
    user: {
      img: user_img,
      name: "About users",
    },
  },
  {
    id: 1,
    title: "messages",
    video: "https://www.freepik.com/free-photos-vectors/default-user",
    view: 1200,
    time: 600,
    user: {
      img: user_img,
      name: "About users",
    },
  },
  {
    id: 1,
    title: "vine",
    video: "https://www.freepik.com/free-photos-vectors/default-user",
    view: 1200,
    time: 600,
    user: {
      img: user_img,
      name: "About users",
    },
  },
  {
    id: 1,
    title: "reels",
    video: "https://www.freepik.com/free-photos-vectors/default-user",
    view: 1200,
    time: 600,
    user: {
      img: user_img,
      name: "About users",
    },
  },
  {
    id: 1,
    title: "shorts",
    video: "https://www.freepik.com/free-photos-vectors/default-user",
    view: 1200,
    time: 600,
    user: {
      img: user_img,
      name: "About users",
    },
  },
  {
    id: 1,
    title: "clip",
    video: "https://www.freepik.com/free-photos-vectors/default-user",
    view: 1200,
    time: 600,
    user: {
      img: user_img,
      name: "About users",
    },
  },
  {
    id: 1,
    title: "religion",
    video: "https://www.freepik.com/free-photos-vectors/default-user",
    view: 1200,
    time: 600,
    user: {
      img: user_img,
      name: "About users",
    },
  },
  {
    id: 1,
    title: "documentary",
    video: "https://www.freepik.com/free-photos-vectors/default-user",
    view: 1200,
    time: 600,
    user: {
      img: user_img,
      name: "About users",
    },
  },
];
